### ISSUE TITLE
will be an update for the mod ?

### ISSUE THREAD

**Issue by xzahalko** [JereKuusela/valheim-server_sync_fix#1]
Hi Jare Kuusela,
we are having some trouble on our server with disconnecting players becouse long time server sync config files ( i suppose )
and we are looking for a mode to correct time before disconnect.

Is this mod correcting the problem ? Will it be upgraded, or can we use it with latest update of Valheim ?
Thank a lot for your help.

**Comment by JereKuusela** [comment]
If Server Sync stops completely working, then yes. As far as I know, it still works as expected.

**Comment by xzahalko** [comment]
ok, thanks :)
